name: ayush_gupta
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.1
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.3
  dropdownfield: ^1.0.3
  flutter_slidable: ^0.6.0


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
   - family: Lobster
     fonts:
       - asset: fonts/Lobster-Regular.ttf

